version: '3.8'

services:
  # PHP service
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - SYMFONY_ENV=dev
    depends_on:
      - database
    networks:
      - mynetwork

  # MySQL service
  database:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: streamplus
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  database_data:

networks:
  mynetwork:
    driver: bridge