services:
  database:
    ports:
      - "3306:3306"

  # Nginx service
  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8080:80"
    networks:
      - mynetwork
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
