parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\ExceptionListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'onKernelException' }

    App\ParamConverter\UserInfoRequestParamConverter:
        arguments:
            $validator: '@validator'
        tags:
            - { name: 'request.param_converter' }

    App\ParamConverter\AddressRequestParamConverter:
        arguments:
            $validator: '@validator'
        tags:
            - { name: 'request.param_converter' }

    App\ParamConverter\PaymentRequestParamConverter:
        arguments:
            $validator: '@validator'
        tags:
            - { name: 'request.param_converter' }

    App\ParamConverter\SubmitRequestParamConverter:
        arguments:
            $validator: '@validator'
        tags:
            - { name: 'request.param_converter' }

    App\Service\Handlers\UserInfoHandler:
        arguments:
            $requestStack: '@request_stack'

    App\Service\Handlers\AddressHandler:
        arguments:
            $requestStack: '@request_stack'

    App\Service\Handlers\PaymentHandler:
        arguments:
            $requestStack: '@request_stack'

    App\Service\Handlers\SubmitHandler:
        arguments:
            $requestStack: '@request_stack'

    App\Validator\Constraints\EmailExistsValidator:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags:
            - { name: validator.constraint_validator }